# Generated by Django 4.2.30 on 2026-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Honeypot Triggered', max_length=255)),
            ],
        ),
    ]
