# Generated by Django 4.2.30 on 2026-04-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_portal', '0011_aitask'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for integrity verification', max_length=64, null=True),
        ),
    ]
